settings:
  gnome:
    - /org/gnome/shell/extensions/quake-terminal/terminal-shortcut: "['F2']"
    - /org/gnome/shell/extensions/quake-terminal/vertical-size: 95
    - /org/gnome/shell/extensions/quake-terminal/terminal-id: "com.mitchellh.ghostty.desktop"